### ISSUE TITLE
Delivery Gateway not available when manually statusing orders

### ISSUE THREAD

**Issue by Theresa288** [meridianww/M4PLBase#339]
When marking order on hand, then outbound, the delivery gateway is not available to manually mark an order complete.

**Comment by Theresa288** [comment]
![bug01](https://user-images.githubusercontent.com/72048984/95582790-219f3f00-0a09-11eb-9f83-1a38dd4af36e.png)

**Comment by nmfujimoto** [comment]
@Theresa288 I believe the reason why no gateway is available is due to the fact that the job has the Outbound gateway in the Tracking tab but it's not marked as completed (see image). Click on the Completed checkbox and see if the next gateway becomes available. 

![image](https://user-images.githubusercontent.com/50392020/95611575-db50dc80-0a16-11eb-933a-0814a730dc03.png)

**Comment by nmfujimoto** [comment]
Believe this is the same issue as #340

**Comment by prashantjustp** [comment]
@nmfujimoto, @bharathrl  This is because of an issue where Gateway(Outbound in this case) did not inherit default completed, which is why It is not showing the Delivery Gateway (Which is resolved but not deployed in prod)
This Gateway(Outbound) has to be manually completed in order to add Delivery Gateway.

**Comment by radha4116** [comment]
@nmfujimoto on Program Home Delivery Out Bound gateway has Next Gateway field empty which was causing the issue not to display next gateway as Delivered, Next gateway field has bee updated to Delivered and verified on Job module as well please cross check and let me know if anything has to be updated.
![339](https://user-images.githubusercontent.com/61678097/95967022-696aff80-0e29-11eb-842b-4fcbc2f09645.PNG)

**Comment by radha4116** [comment]
Above comment has been verified on Staging server

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.
