### ISSUE TITLE
Add Select All For Grid

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#353]
Add Select All option to grid so user can select all rows.

**Comment by nmfujimoto** [comment]
The dashboard and job grid should have the Select All option in the grid header row to select all records.

**Comment by KamalAdhikary** [comment]
@nmfujimoto 
Feature has been implemented and reflecting in local QA server (testing in progress)
One limitation  of "Select All" feature 
1. By clicking on "Select All" check box current page rows/order are getting selected, not for ALL pages, because of our data grid is collecting the records page wise with server side call/load.
2. But still user can select "Select All" check box for multi pages by moving page to page.

**Comment by Madhusmi** [comment]
@nmfujimoto The Feature has tested on QA server and it working as expected.
