### ISSUE TITLE
Program Price/Cost Code NAV Web Calls

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#41]
The Program Price Code tab retrieves NAV Price Lists for the Sales Price web service call. 
The Program Cost Code tab retrieves NAV Price Lists for the Purchase Price web service call.
The current implementation is incorrectly mapped with the Price Code tab calling the NAV Purchase Price web call.

**Comment by prashantaggarwal1999** [comment]
This issue was present on the 1010 server as Price/Cost rates were considered as integer while it was coming as a decimal from the service which was causing the issue while deserializing the data into C# model. Now we have changed the data type to decimal nullable so that it can handle the rates properly as well as accept the null. API call also gets updated to call the correct API for Price and Cost code on 1010 server. Please check and let us know if any other wrong behaviour you will observe.
