### ISSUE TITLE
Company Field Not Showing Names In Contacts

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#43]
The Company Name field in the Contacts grid is blank for all records. If you enable filtering you can type in a company name and it will filter the results but the column is still blank.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/63469956-45c44900-c420-11e9-8b40-779dddb86a02.png)

![image](https://user-images.githubusercontent.com/50392020/63469962-48bf3980-c420-11e9-9c9f-91bc7a8c8e72.png)

**Comment by prashantaggarwal1999** [comment]
Hi Nathan, We have added a new column with the name Company during the implementation of Company Dropdown implementation. There was a column with the name Company Name already present which was getting used in past. As discussed initially we have not deleted the Company Name Column. To correct this issue now we have removed the Company Name From Column ALias so that it will not be visible on the UI.
