### ISSUE TITLE
Browser Error In Chrome

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#49]
When trying to expand the Location Master records in the Program Price/Cost tabs I constantly receive an error from Chrome stating the request is too long. 

It seems that each time I expand a Master record to see the details (vendor locations) the error is displayed for each Master-Detail expansion, e.g. first Master record I expand the error is displayed once, and if I expand a second location then two error messages are display, and expanding three locations displays three error messages, etc.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/63543466-c5611f00-c4d7-11e9-8165-4736f456d7cb.png)

**Comment by prashantaggarwal1999** [comment]
Hi Nathan, I have tried to reproduce the error for me, it is happening only for chrome and after analysis, I got to know that the root cause of the issue os corrupt cookies as I have not cleared the cookies from few days.
This error is caused by a corrupt cookie for the website you are trying to view, so to clear it all you need to do is clear the bad cookie(s) for that website.

In Chrome, go to...
chrome://settings/cookies
(Or manually go to Settings->Advanced Settings->Privacy->Content->All Cookies and Site data)
From there, you can search for cookies that match the site you are having problems on. Finally, click "remove all" for the matching cookies.
